apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835-final
  region: "us-east-1"
  version: "1.29"  # or "1.30" if supported

iam:
  serviceRoleARN: arn:aws:iam::590719902757:role/LabRole

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 2
    instanceType: t3.small
    ssh:
      enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::590719902757:role/LabRole
