apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: flask-app
          image: 590719902757.dkr.ecr.us-east-1.amazonaws.com/app-repo:latest
          ports:
            - containerPort: 81
          env:
            - name: DBHOST
              value: mysql
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DBUSER
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DBPWD
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: IMAGE_URL
            - name: APP_HEADER_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_HEADER_NAME
            - name: APP_COLOR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_COLOR
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AWS_SESSION_TOKEN
