apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: final
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80              # Public port (browser sends request to this)
      targetPort: 8080   # What your container is listening on
  type: LoadBalancer
