apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: final
type: Opaque
data:
  DBUSER: cm9vdA==
  DBPWD: cHc=
  AWS_ACCESS_KEY_ID: QVNJQVlUQ05HTVFTVDI3WDZRNVM=
  AWS_SECRET_ACCESS_KEY: S1NEdERNckRaaEVhRGNGSXlIOWplcjhybHdNemJ3d0pFMkFYTEhObw==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVDVWFDWFZ6TFhkbGMzUXRNaUpITUVVQ0lEOTJYdGtHWmEyV083SnhXeXVPbDNoNEo3c3NjVlFDM055dEVyVVM3amVNQWlFQXd2OG9VQ2Y0RytTMEFvc2g2bjdCT2JUY3JpZWhWdCszRmI4SEhIQTlnUFFxdFFJSW52Ly8vLy8vLy8vL0FSQUNHZ3cxT1RBM01UazVNREkzTlRjaUREUWJZcEppNmwzTlNybXE2U3FKQWsvdFpBSU5neVRPYjVaWmtZUEtYYWh0UXVMY085eUV4V3lTUVg2Y0l2WmE1R0UvVk5LMlNjVHMrbFJWNmtpa3lpbDlRRUlnbFEvTHpkdWFKYWpPenkxNThFVHVjVlFJWFcyeU9uS0lLbDJZU1hoL2IwWkhuWThvWm52OUg4eG1ZOGZMS1I0eU14ZjBBMmY0RmNjZVkwb0JodFduQVlZcWRqTlBUcUZaOCtDajdhV1hTdmx6Y3IwYmJhUkRSenMzL0NvaWhhcklUK00xR3BlL0ZyUzllR09GN1dPS3luTlA5QkZzRTJsRWJRNHU0UEp0aUhldjRPRXB6VlRmeWtHTkVmbWZhejZ4S1I0aEpDUkdXdHpFc09uMlFVUEpiOVpSN0JRL0dCTkhPRWZLNmxyNkpWaEd4KzBqQjJBa2Q1T0cyLzNLMDJuTlIzZVpiVDl6WEtSai9YZEVYMzBlYXFDdVhGQXcwSkhkdndZNm5RSFpKZld6Y3NJOEpzUHJLK3JjcU15MEsyWnVqdnUrSHFuQkM4OG1weGswWUxLYi9VQmk0QjZYTmRGVGhUMnhBZTVqbkdCVmhvSnpyV1dlZ0dURXozbGV3M3RISjVIZTlCcTFqZ3Z2bGVHTG5JY2NUS0R6RU1GR2ZNNklHYm9xUHdud1pod3JFK2UyOTVOd0JQK2Ewc3d6Zk9WRHZONWZCSnZ3bVFQMTVRaUY4MXRZeThzMGVTK1Q4WWFLSklTa1NMYmUxV09JSnc5SzZGNURjSi92